### ISSUE TITLE
新デザインの埋め込みで崩れる

### ISSUE THREAD

**Issue by hinaloe** [RecoTwExplorer/RecoTwExplorer#109]
![image](https://user-images.githubusercontent.com/5253290/82863789-018d4880-9f5e-11ea-9350-454727b25880.png)

細長い

**Comment by hinaloe** [comment]
![image](https://user-images.githubusercontent.com/5253290/82863888-38fbf500-9f5e-11ea-94f4-ab685e4d4cac.png)
404でエラーなやつもだめ

**Comment by chitoku-k** [comment]
A/B テストで表示が切り替わるため常に再現するわけではない

**Comment by chitoku-k** [comment]
## 新デザインの変更点
- `<iframe>` の `src` 属性を使った埋め込みツイート表示用ページが書き出されるようになった
  - このページは `location.search` の `id` パラメーターからツイートの ID を取得して表示する
  - このページ内でツイートの取得に失敗しても、`createTweet` にチェインした `Promise#then()` は resolve も reject もされない（オワオワリ）
- `twitter.com` とオリジンが違うので iframe のページ内に最大幅がハードコード（550px）されているのを変更できない

## 解決策（案）
- `createTweet` をやめて、このツイート表示用ページを直接叩く
  - 表示の可否とレイアウトの変更のために RecoTwStub でプロキシーしてオリジンを揃えたい

**Comment by chitoku-k** [comment]
✓ 404 エラーは改修されていた
