### ISSUE TITLE
ツイート登録機能を改善する

### ISSUE THREAD

**Issue by chitoku-k** [RecoTwExplorer/RecoTwExplorer#16]
ツイート登録ウィンドウの実装を一部変更して機能を追加・修正する
1. ID または URL が入力された場合の判定に「ツイートが登録されているか」を加える（別エラー扱いにした方がよい）
2. （すべての）テキスト ボックスが空欄でも登録できてしまう仕様を修正する

**Comment by hinaloe** [comment]
埋め込みツイート使ってプレビューとか…………なし？()

**Comment by chitoku-k** [comment]
@hinaloe 将来的に複数のツイートの同時登録が可能になった場合を見据えて、それに見合うレイアウトがあれば、検討の余地はあるかも。

**Comment by hinaloe** [comment]
```
input[required]
input[pattern]
```
