### ISSUE TITLE
一部デバイスでグラフが横にはみ出る

### ISSUE THREAD

**Issue by chitoku-k** [RecoTwExplorer/RecoTwExplorer#23]
## 概要

スマートフォンなどの画面幅の狭い環境で表示した場合に、統計情報タブのグラフ表示が画面幅より広いためそれがはみ出て表示される。
## 原因

Google Chart に値を即値で設定しているため。
## 対処

次のうちいずれか 1 つを以ってこの問題の対処とする。
- スクリプトではなく外側のコンテナ要素にサイズを設定し、スクリプトからは相対サイズ指定で表示する。画面幅が画面の回転などで動的に変化した場合の対応については引き続き調査中。
- Google Chart 以外のレスポンシブ デザインに対応したライブラリを使用する。

**Comment by hinaloe** [comment]
IMO: 02cab30a0d6c09ac76dd6ed1cec9e89a1e1c51c6

**Comment by chitoku-k** [comment]
CSS での指定のほうが妥当かな、と。ただ 02cab30 も ccc81c4 も

> 画面幅が画面の回転などで動的に変化した場合の対応

を満たすものではないので、ライブラリを変更したほうが良さそう
