### ISSUE TITLE
黒歴史をキャッシュするようにする

### ISSUE THREAD

**Issue by chitoku-k** [RecoTwExplorer/RecoTwExplorer#36]
GET `tweet/get_tweet_all` に `since_id` が実装されたため黒歴史に対するキャッシュ処理を実装する。
http://recotw.black/api.html#list

> since_id=OFFSET optional 
> ここで指定した id (tweet_id ではありません)以降のツイートが返ってきます。

**Comment by hinaloe** [comment]
Merged #40
