### ISSUE TITLE
ショートカットキーの実装

### ISSUE THREAD

**Issue by chitoku-k** [RecoTwExplorer/RecoTwExplorer#37]
そろそろショートカットキーへの対応をば。
（未定）
- 各タブ・ポップアップの表示切り替え
- 検索ボックスへのフォーカス
- 並び替えの選択

`Esc`
- 統計情報のフィルタ検索の解除
- 検索ボックスからのフォーカス解除

意見募集します。

**Comment by hinaloe** [comment]
(お決まりの) **v i m キ ー バ イ ン ド**

**Comment by chitoku-k** [comment]
Vim わかんないけどスクロールくらい？

**Comment by ayatk** [comment]
ショートカットキーって設定で変えれるようにするの?

**Comment by chitoku-k** [comment]
そうなったらめっちょ大変だな(++)
