### ISSUE TITLE
複数画像表示の際の角丸が調整されていない

### ISSUE THREAD

**Issue by chitoku-k** [RecoTwExplorer/RecoTwExplorer#46]
## 概要

![image](https://cloud.githubusercontent.com/assets/6535425/6202542/d00fe7d6-b534-11e4-98c6-79f1abbbfd06.png)
## 原因

`iframe` への CSS 上書き処理の漏れ
https://github.com/RecoTwExplorer/RecoTwExplorer/blob/8601dee59cc6c46cb294a69c9d2e4daa842fdcf5/src/ts/recotw.ts#L787-L795
## 対処

画像 2・3 枚パターンと画像 4 枚パターンの 2 種類ある模様なので当該箇所の `border-radius` 指定を上書きするよう修正。

**Comment by hinaloe** [comment]
Fixed #48
