### ISSUE TITLE
Twitter 埋め込みウィジェットのデザイン変更対応

### ISSUE THREAD

**Issue by chitoku-k** [RecoTwExplorer/RecoTwExplorer#52]
本家がフラットデザインになったのでこれまで適用していたスタイルを変更する必要がありそう。

![cdsol_gveaikenk](https://cloud.githubusercontent.com/assets/6535425/7300161/8397645e-ea15-11e4-8608-1d75261d733d.png)

**Comment by hinaloe** [comment]
fixed https://github.com/RecoTwExplorer/RecoTwExplorer/commit/c1cbc92c973639e9325a0bca8440545d990dfc3d

**Comment by chitoku-k** [comment]
余白が出るようになってしまった……  
<img width="671" alt="" src="https://cloud.githubusercontent.com/assets/6535425/15184708/435e9ce6-17d1-11e6-83e8-01b0e5cfe158.png">

**Comment by hinaloe** [comment]
つらいなぁ（よろしく

**Comment by hinaloe** [comment]
これってChrome系(というかCustomElements対応ブラウザ)だけ？

**Comment by hinaloe** [comment]
Shadow DOMつらいなぁ
