### ISSUE TITLE
iOS 9 の Web アプリモードで横画面で起動したときにステータスバー分の領域が確保されない

### ISSUE THREAD

**Issue by chitoku-k** [RecoTwExplorer/RecoTwExplorer#83]
# 概要

表題どおり。
# 原因

横画面の時は
`window.innerHeight` = 768
`screen.height` = 1024

**Comment by hinaloe** [comment]
こういうこと？
![image](https://cloud.githubusercontent.com/assets/5253290/12236540/cf4c1c92-b8bd-11e5-9003-7ed74742d855.png)

**Comment by chitoku-k** [comment]
そういうこと！
`Controller` の初期化で使われている条件がスルーされちゃうのがよくないみたい
