### ISSUE TITLE
デプロイ方法とディレクトリ構成の変更

### ISSUE THREAD

**Issue by hinaloe** [RecoTwExplorer/RecoTwExplorer#9]
現状ではメインブランチをgh-pagesに当ててるけど一端開発ブランチをmaster/devにしデプロイはciに任せたい。
また合わせて`dest`をメインリポ管理下から外し、gulp-userefを用いたhtmlビルド

**Comment by hinaloe** [comment]
@chitoku-k 

```
┬ * dest ┬ index.html
│　　　 ├ css ┄ style.min.css
│　　　 ├ img ┄ (images)
│　　　 ├ font┄ (fonts)
│　　　 └ js ┄ recotw.min.js,vendor.min.js
├ * dev ─ js ─ recotw.js, recotw.js.map
├ src ┬ ts ───
│　　└ SASS?─
├ images
├ lib
├ *node_modules
├
...(以下既存ファイル) 
※　*はgitignore
```

って感じの構成でおｋ？

**Comment by chitoku-k** [comment]
@hinaloe ルートにない `index.html` って使えるの？

**Comment by hinaloe** [comment]
@chitoku-k destをルートにしてgh-pagesにPushする感じ。(一応現状のindex.htmlはルートに残してる)

**Comment by chitoku-k** [comment]
@hinaloe 了解！

**Comment by chitoku-k** [comment]
@hinaloe ブランチ切ってても関係なくビルドされて `gh-pages` に Push されるんだけど…
（追記）プルリクエストによるもの
