### ISSUE TITLE
プロキシーを設定する

### ISSUE THREAD

**Issue by chitoku-k** [RecoTwExplorer/RecoTwExplorer#90]
ローカルでもリモートでも動作するプロキシーのような何かが必要。

**Comment by hinaloe** [comment]
何で書く？

**Comment by chitoku-k** [comment]
のーど！

**Comment by hinaloe** [comment]
とりあえずBrowserSync用だけ強引に対応してみた、型定義とか思いっきし不足してるのできになるならなんとか……

3b7de86f8804a74a1098298c8d2b9b8c3775a0f1

**Comment by chitoku-k** [comment]
Twitter アイコン向け proxy を書きたい
